In [1]:
import pandas as pd
import numpy as np
import random
from statsmodels.stats.weightstats import ztest

In [2]:
data = pd.read_csv('train_data.csv')
data

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
0,0,1,0,1,0.2750,0.014151,0,0,1,0.1,1,0,0,0,0,0,1
1,1,2,1,0,0.4750,0.139136,1,0,0,0.1,1,0,0,0,1,0,0
2,2,3,1,0,0.3250,0.015469,0,0,1,0.0,0,0,0,1,0,0,1
3,3,4,1,0,0.4375,0.103644,1,0,0,0.1,1,0,0,0,0,0,1
4,4,5,0,1,0.4375,0.015713,0,0,1,0.0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
787,787,788,0,1,0.1000,0.056848,0,0,1,0.5,0,0,1,0,0,1,0
788,788,789,1,1,0.0125,0.040160,0,0,1,0.3,0,0,1,0,0,0,1
789,789,790,0,1,0.5750,0.154588,1,0,0,0.0,1,0,0,0,1,0,0
790,790,791,0,1,0.3500,0.015127,0,0,1,0.0,1,0,0,0,0,1,0
791,791,792,0,1,0.2000,0.050749,0,1,0,0.0,1,0,0,0,0,0,1

In [3]:
data_p1 = data[data['Pclass_1'] == 1]
data_p23 = data[(data['Pclass_2'] == 1) | (data['Pclass_3'] == 1)]
data_p1.describe()

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
count,193.000000,193.000000,193.000000,193.000000,193.000000,193.000000,193.0,193.0,193.0,193.000000,193.000000,193.000000,193.000000,193.000000,193.000000,193.000000,193.000000
mean,415.227979,416.227979,0.616580,0.580311,0.460778,0.172263,1.0,0.0,0.0,0.078756,0.756477,0.015544,0.010363,0.217617,0.404145,0.010363,0.580311
std,220.545653,220.545653,0.487484,0.494792,0.179062,0.157645,0.0,0.0,0.0,0.105151,0.430325,0.124025,0.101532,0.413698,0.492002,0.101532,0.494792
min,1.000000,2.000000,0.000000,0.000000,0.011500,0.000000,1.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,257.000000,258.000000,0.000000,0.000000,0.350000,0.067640,1.0,0.0,0.0,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,435.000000,436.000000,1.000000,1.000000,0.437500,0.129995,1.0,0.0,0.0,0.100000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,599.000000,600.000000,1.000000,1.000000,0.587500,0.212559,1.0,0.0,0.0,0.100000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
max,789.000000,790.000000,1.000000,1.000000,1.000000,1.000000,1.0,0.0,0.0,0.500000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [4]:
data_p23.describe()

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
count,599.000000,599.000000,599.000000,599.000000,599.000000,599.000000,599.0,599.000000,599.000000,599.000000,599.000000,599.000000,599.000000,599.000000,599.000000,599.000000,599.000000
mean,389.143573,390.143573,0.312187,0.669449,0.338429,0.030013,0.0,0.275459,0.724541,0.091820,0.741235,0.001669,0.050083,0.207012,0.115192,0.118531,0.766277
std,231.185283,231.185283,0.463773,0.470805,0.145577,0.023905,0.0,0.447119,0.447119,0.167262,0.438322,0.040859,0.218300,0.405503,0.319520,0.323506,0.423552
min,0.000000,1.000000,0.000000,0.000000,0.008375,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,185.000000,186.000000,0.000000,0.000000,0.262500,0.015330,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
50%,391.000000,392.000000,0.000000,1.000000,0.350000,0.020495,0.0,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,592.500000,593.500000,1.000000,1.000000,0.387500,0.037826,0.0,1.000000,1.000000,0.100000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,791.000000,792.000000,1.000000,1.000000,0.881250,0.143462,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [5]:
data_p1['Survived'].mean(), data_p23['Survived'].mean()

(np.float64(0.616580310880829), np.float64(0.3121869782971619))

бутстрэп доверительного интервала разницы долей выживших

In [6]:
ships = []

for _ in range(10000):
    p1 = pd.Series(random.choices(data_p1['Survived'].values, k=data_p1.shape[0])).mean()
    p23 = pd.Series(random.choices(data_p23['Survived'].values, k=data_p23.shape[0])).mean()
    ships.append(p1 - p23)

In [7]:
np.quantile(ships, q=[0.025, 0.975])

array([0.22534686, 0.3825735 ])

ручная z-статистика и z-тест

In [8]:
(data_p1['Survived'].mean() - data_p23['Survived'].mean()) / ((data['Survived'].mean() * (1 - data['Survived'].mean())) / (len(data['Survived']))) ** 0.5

np.float64(17.59316840863016)

In [9]:
ztest(data_p1.Survived, data_p23.Survived)

(np.float64(7.830586337563221), np.float64(4.855999313122105e-15))